# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='wished_by',
            new_name='wishers',
        ),
    ]
